### ISSUE TITLE
delete games don't work

### ISSUE THREAD

**Issue by alberttwong** [elovation/elovation#128]
clicking on the delete game link gives you an error.

```
024-09-09 19:09:10 Started GET "/players/4" for 192.168.65.1 at 2024-09-10 02:09:10 +0000
2024-09-09 19:09:10 Processing by PlayersController#show as HTML
2024-09-09 19:09:10   Parameters: {"id"=>"4"}
2024-09-09 19:09:10   Player Load (0.2ms)  SELECT "players".* FROM "players" WHERE "players"."id" = $1 LIMIT $2  [["id", 4], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/controllers/players_controller.rb:45:in `set_player'
2024-09-09 19:09:10   Rendering layout layouts/application.html.erb
2024-09-09 19:09:10   Rendering players/show.html.erb within layouts/application
2024-09-09 19:09:10   Result Exists? (0.5ms)  SELECT 1 AS one FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 LIMIT $2  [["player_id", 4], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/views/players/show.html.erb:8
2024-09-09 19:09:10   CACHE Result Exists? (0.0ms)  SELECT 1 AS one FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 LIMIT $2  [["player_id", 4], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/views/players/show.html.erb:16
2024-09-09 19:09:10   Result Load (0.3ms)  SELECT "results".* FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 ORDER BY results.created_at DESC LIMIT $2  [["player_id", 4], ["LIMIT", 5]]
2024-09-09 19:09:10   ↳ app/views/shared/_results.html.erb:2
2024-09-09 19:09:10   Team Load (0.1ms)  SELECT "teams".* FROM "teams" WHERE "teams"."result_id" = $1  [["result_id", 2]]
2024-09-09 19:09:10   ↳ app/models/result.rb:64:in `all?'
2024-09-09 19:09:10   Player Load (0.2ms)  SELECT "players".* FROM "players" INNER JOIN "memberships" ON "players"."id" = "memberships"."player_id" WHERE "memberships"."team_id" = $1  [["team_id", 3]]
2024-09-09 19:09:10   ↳ app/models/result.rb:65:in `all?'
2024-09-09 19:09:10   Game Load (0.2ms)  SELECT "games".* FROM "games" WHERE "games"."id" = $1 ORDER BY updated_at DESC LIMIT $2  [["id", 2], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/models/result.rb:66:in `block (2 levels) in most_recent?'
2024-09-09 19:09:10   Result Load (0.3ms)  SELECT "results".* FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 AND "results"."game_id" = $2 ORDER BY created_at DESC LIMIT $3  [["player_id", 1], ["game_id", 2], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/models/result.rb:66:in `block (2 levels) in most_recent?'
2024-09-09 19:09:10   Player Load (0.1ms)  SELECT "players".* FROM "players" INNER JOIN "memberships" ON "players"."id" = "memberships"."player_id" WHERE "memberships"."team_id" = $1  [["team_id", 4]]
2024-09-09 19:09:10   ↳ app/models/result.rb:65:in `all?'
2024-09-09 19:09:10   Result Load (0.3ms)  SELECT "results".* FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 AND "results"."game_id" = $2 ORDER BY created_at DESC LIMIT $3  [["player_id", 4], ["game_id", 2], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/models/result.rb:66:in `block (2 levels) in most_recent?'
2024-09-09 19:09:10   Team Count (0.2ms)  SELECT COUNT(*) FROM "teams" WHERE "teams"."result_id" = $1  [["result_id", 2]]
2024-09-09 19:09:10   ↳ app/models/result.rb:52:in `tie?'
2024-09-09 19:09:10   Team Count (0.2ms)  SELECT COUNT(*) FROM "teams" WHERE "teams"."result_id" = $1 AND "teams"."rank" = $2  [["result_id", 2], ["rank", 1]]
2024-09-09 19:09:10   ↳ app/models/result.rb:52:in `tie?'
2024-09-09 19:09:10   CACHE Result Load (0.0ms)  SELECT "results".* FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 AND "results"."game_id" = $2 ORDER BY created_at DESC LIMIT $3  [["player_id", 1], ["game_id", 2], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/models/result.rb:66:in `block (2 levels) in most_recent?'
2024-09-09 19:09:10   CACHE Result Load (0.0ms)  SELECT "results".* FROM "results" INNER JOIN "teams" ON "results"."id" = "teams"."result_id" INNER JOIN "memberships" ON "teams"."id" = "memberships"."team_id" WHERE "memberships"."player_id" = $1 AND "results"."game_id" = $2 ORDER BY created_at DESC LIMIT $3  [["player_id", 4], ["game_id", 2], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/models/result.rb:66:in `block (2 levels) in most_recent?'
2024-09-09 19:09:10   Rendered collection of shared/_result.html.erb [1 times] (Duration: 12.5ms | Allocations: 9662)
2024-09-09 19:09:10   Rendered shared/_results.html.erb (Duration: 13.9ms | Allocations: 10475)
2024-09-09 19:09:10   Rating Load (0.1ms)  SELECT "ratings".* FROM "ratings" WHERE "ratings"."player_id" = $1  [["player_id", 4]]
2024-09-09 19:09:10   ↳ app/views/players/show.html.erb:25
2024-09-09 19:09:10   CACHE Game Load (0.0ms)  SELECT "games".* FROM "games" WHERE "games"."id" = $1 ORDER BY updated_at DESC LIMIT $2  [["id", 2], ["LIMIT", 1]]
2024-09-09 19:09:10   ↳ app/views/players/_rating.html.erb:1
2024-09-09 19:09:10   Rendered collection of players/_rating.html.erb [1 times] (Duration: 1.0ms | Allocations: 814)
2024-09-09 19:09:10   Rendered players/show.html.erb within layouts/application (Duration: 20.2ms | Allocations: 14551)
2024-09-09 19:09:10   Rendered layout layouts/application.html.erb (Duration: 26.3ms | Allocations: 16938)
2024-09-09 19:09:10 Completed 200 OK in 30ms (Views: 24.3ms | ActiveRecord: 2.8ms | Allocations: 17697)
2024-09-09 19:09:10 
2024-09-09 19:09:10 
2024-09-09 19:09:12 Started GET "/games/2/results/2" for 192.168.65.1 at 2024-09-10 02:09:12 +0000
2024-09-09 19:09:12   
2024-09-09 19:09:12 ActionController::RoutingError (No route matches [GET] "/games/2/results/2"):
2024-09-09 19:09:12
```

**Comment by alberttwong** [comment]
Not a ruby guy......  let's see if my google-fu is any good.
